--item
data:extend({
{
  type = "item",
  name = "rocket-turret-mk1",
  icon = "__Rocket_Turrets__/graphics/icon/turret-rocket-mk1-icon.png",
  icon_size = 32,
  subgroup = "defensive-structure",
  order = "b[turret]-c[base]-d[rocket-mk1]",
  place_result = "rocket-turret-mk1",
  stack_size = 50,
},
{
  type = "item",
  name = "rocket-turret-mk2",
  icon = "__Rocket_Turrets__/graphics/icon/turret-rocket-mk2-icon.png",
  icon_size = 32,
  subgroup = "defensive-structure",
  order = "b[turret]-c[base]-d[rocket-mk2]",
  place_result = "rocket-turret-mk2",
  stack_size = 50,
},
{
  type = "item",
  name = "rocket-turret-mk3",
  icon = "__Rocket_Turrets__/graphics/icon/turret-rocket-mk3-icon.png",
  icon_size = 32,
  subgroup = "defensive-structure",
  order = "b[turret]-c[base]-d[rocket-mk3]",
  place_result = "rocket-turret-mk3",
  stack_size = 50,
},
{
  type = "item",
  name = "rocket-turret-mk4",
  icon = "__Rocket_Turrets__/graphics/icon/turret-rocket-mk4-icon.png",
  icon_size = 32,
  subgroup = "defensive-structure",
  order = "b[turret]-c[base]-d[rocket-mk4]",
  place_result = "rocket-turret-mk4",
  stack_size = 50,
},
{
  type = "item",
  name = "rocket-turret-mk5",
  icon = "__Rocket_Turrets__/graphics/icon/turret-rocket-mk5-icon.png",
  icon_size = 32,
  subgroup = "defensive-structure",
  order = "b[turret]-c[base]-d[rocket-mk5]",
  place_result = "rocket-turret-mk5",
  stack_size = 50,
},
})
